---
name: Agent DVR
version: 4.2.9.0
slug: ispyagentdvr
description: iSpy's Agent DVR, a standalone DVR service to manage IP cameras
url: https://registry.hub.docker.com/r/doitandbedone/ispyagentdvr
codenotary: doitandbedone
webui: "http://[HOST]:[PORT:8090]"
startup: system
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - ssl
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: TasmoAdmin web interface
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str