---
version: 2.2.0
slug: deepstack-trainer
name: DeepStack Trainer
description: DeepStack Trainer - клиент c графическим интерфейсом
url: https://github.com/t0mer/deepstack-trainer
webui: http://[HOST]:[PORT:8080]
codenotary: divanx10
panel_icon: mdi:FaceRecognition
arch:
  - amd64
hassio_api: true
host_network: true
image: techblog/deepstack-trainer
init: false
map:
  - config:rw
  - media:rw
startup: application
boot: auto
ports:
  8080/tcp: 7100
ports_description:
  8080/tcp: Optional. Port of your deepstack server
environment:
  DEEPSTACK_HOST_ADDRESS: http://homeassistant:7000
